"""
Apply sector classifications from config/Others_Sector-SubSectors_List.xlsx
to sector_master in the DuckDB database.

Actions:
  1. Update 363 'Others' stocks with proper sector + sub-sector + category
  2. Mark all ETF symbols (explicit + auto-detected) as sector='ETF'
  3. Persist all changes to config/sector_overrides.csv for re-seeding

Run:
    python scripts/apply_sector_classifications.py
    python scripts/apply_sector_classifications.py --dry-run
"""
from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.core.logging import get_logger
from src.data.repository import get_repository
from src.data.schema import initialize_schema

log = get_logger(__name__)

EXCEL_PATH     = PROJECT_ROOT / "config" / "Others_Sector-SubSectors_List.xlsx"
OVERRIDES_PATH = PROJECT_ROOT / "config" / "sector_overrides.csv"

# ETF-pattern symbols not listed in the 'Excluded' sheet but clearly funds/ETFs
_ADDITIONAL_ETFS: frozenset[str] = frozenset({
    "AUTOBEES", "BANK10ADD", "BANKBEES", "CASHIETF", "CPSEETF",
    "GOLD1", "GOLDADD", "GOLDBEES", "GOLDBETA", "GOLDCASE",
    "GOLDETF", "GOLDIETF", "HDFCSML250", "HNGSNGBEES",
    "ITBEES", "JUNIORBEES",
    "LIQUID", "LIQUID1", "LIQUIDADD", "LIQUIDBEES", "LIQUIDBETF",
    "LIQUIDCASE", "LIQUIDETF", "LIQUIDIETF", "LIQUIDPLUS",
    "MID150BEES", "MIDCAPETF", "MON100",
    "NIFTYBEES", "NIFTYIETF", "PHARMABEES", "PSUBNKBEES", "PVTBANIETF",
    "SBILIQETF", "SETFGOLD", "SETFNIF50",
    "SILVER", "SILVER1", "SILVERADD", "SILVERBEES", "SILVERBETA",
    "SILVERCASE", "SILVERIETF", "SMALLCAP",
})


def _load_excel() -> tuple[pd.DataFrame, pd.DataFrame]:
    xl = pd.ExcelFile(EXCEL_PATH)
    classified = pd.read_excel(xl, sheet_name="Classified Stocks")
    etfs = pd.read_excel(xl, sheet_name="Excluded (ETFs)")
    classified["Symbol"] = classified["Symbol"].str.strip()
    etfs["Symbol"]       = etfs["Symbol"].str.strip()
    return classified, etfs


def _clean_str(val) -> str:
    s = str(val or "").strip()
    return "" if s.lower() == "nan" else s


def _build_overrides_df(classified: pd.DataFrame, all_etf_symbols: set[str]) -> pd.DataFrame:
    rows = []

    for _, row in classified.iterrows():
        rows.append({
            "symbol":   row["Symbol"],
            "sector":   row["Sector"],
            "industry": row["Sub-Sector"],
            "category": _clean_str(row.get("Category", "")),
            "notes":    _clean_str(row.get("Notes", "")) or "Excel classification",
        })

    for sym in sorted(all_etf_symbols):
        rows.append({
            "symbol":   sym,
            "sector":   "ETF",
            "industry": "ETF / Index Fund",
            "category": "",
            "notes":    "ETF / Index Product — excluded from sector analysis",
        })

    return pd.DataFrame(rows)


def _apply_to_db(overrides_df: pd.DataFrame, repo, dry_run: bool) -> dict[str, int]:
    existing = repo.query(
        "SELECT symbol, company_name, market_cap_category FROM sector_master"
    )
    existing_map = {r["symbol"]: r for _, r in existing.iterrows()}

    now = datetime.now()
    upsert_rows = []
    for _, ov in overrides_df.iterrows():
        sym = ov["symbol"]
        ex  = existing_map.get(sym, {})
        upsert_rows.append({
            "symbol":              sym,
            "company_name":        ex.get("company_name",        "") or "",
            "sector":              ov["sector"],
            "industry":            ov["industry"],
            "category":            ov.get("category", "") or "",
            "market_cap_category": ex.get("market_cap_category", "") or "",
            "last_updated":        now,
        })

    upsert_df       = pd.DataFrame(upsert_rows)
    classified_count = len(overrides_df[overrides_df["sector"] != "ETF"])
    etf_count        = len(overrides_df[overrides_df["sector"] == "ETF"])

    if not dry_run:
        from src.data.repository import upsert_sector_master
        upsert_sector_master(upsert_df)

    return {"classified": classified_count, "etf": etf_count, "total": len(upsert_df)}


def _save_overrides_csv(overrides_df: pd.DataFrame, dry_run: bool) -> None:
    header = (
        "# Sector overrides — manually assign stocks to sectors / industries / categories\n"
        "# Format: symbol,sector,industry,category,notes\n"
        "# Generated by scripts/apply_sector_classifications.py\n"
    )
    csv_body = overrides_df.to_csv(index=False)
    if dry_run:
        log.info("[DRY-RUN] Would write %d rows to %s", len(overrides_df), OVERRIDES_PATH)
        return
    OVERRIDES_PATH.write_text(header + csv_body, encoding="utf-8")
    log.info("Wrote %d rows to %s", len(overrides_df), OVERRIDES_PATH)


def run(dry_run: bool = False) -> None:
    log.info("Loading Excel: %s", EXCEL_PATH)
    classified, etfs_sheet = _load_excel()

    explicit_etf_set = set(etfs_sheet["Symbol"])
    all_etf_symbols  = explicit_etf_set | _ADDITIONAL_ETFS

    log.info(
        "Excel: %d classified stocks, %d explicit ETFs, %d additional ETFs detected",
        len(classified), len(explicit_etf_set), len(_ADDITIONAL_ETFS),
    )

    # Ensure the category column exists before upserting
    initialize_schema()

    overrides_df = _build_overrides_df(classified, all_etf_symbols)
    repo         = get_repository()
    counts       = _apply_to_db(overrides_df, repo, dry_run)

    prefix = "[DRY-RUN] " if dry_run else ""
    log.info(
        "%sUpdated sector_master: %d stocks classified, %d marked as ETF (total %d rows)",
        prefix, counts["classified"], counts["etf"], counts["total"],
    )

    _save_overrides_csv(overrides_df, dry_run)

    if not dry_run:
        # Sample verification
        sample = repo.query("""
            SELECT sector, industry, category, COUNT(*) AS stocks
            FROM sector_master
            WHERE sector NOT IN ('ETF','Others','')
              AND category != ''
            GROUP BY sector, industry, category
            ORDER BY sector, industry, stocks DESC
            LIMIT 20
        """)
        log.info("Sample category distribution:\n%s", sample.to_string(index=False))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would change without writing")
    args = parser.parse_args()
    run(dry_run=args.dry_run)


if __name__ == "__main__":
    main()
